Project 4: Apple clone web page
tnyandoro/apple_clone_webpage pull request #1
Opened 2020-09-06 12:11 UTC by enaburekhan

**Apple original web page cloned by Eric Enaburekhan and Tendai Nyandoro.**
In this project, we:

- use images as a background using flex
- Add gradients to elements using CSS
- use flex, grid and float for positioning.
- The goal was to make a clone of an old version of Apple website webpage

2020-09-06 14:07 UTC, Spayco requested changes
# Invalid 🛑 

## This project cannot be reviewed without the linter checks, please add the [linters config](https://github.com/microverseinc/linters-config) and ask for another review


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-09-06 17:20 UTC, elmejdki requested changes
# status: require changes :recycle: 
## Hi, you need more work :hammer: :wrench: :toolbox: to get it much better :100: :+1: , please fix the issues bellow.

- [ ] Fix the linter errors:
![image](https://user-images.githubusercontent.com/34653764/92330867-308d7d00-f06a-11ea-83b4-9d2dd0feab33.png)

- [ ] You should not use images over text:
![image](https://user-images.githubusercontent.com/34653764/92331015-39328300-f06b-11ea-8a18-20a21480ed1a.png)

- [ ] fix the search input it's not well designed:
![image](https://user-images.githubusercontent.com/34653764/92331040-75fe7a00-f06b-11ea-83a3-b5ec9b060692.png)

- [ ] Fix the text inside the navbar items they should be perfectly centered.
![image](https://user-images.githubusercontent.com/34653764/92331047-8a427700-f06b-11ea-8b6c-6f507389c723.png)

- [ ] the main image should cover the whole page. and it should be set on the background of the page. you can use background size and position properties to achieve that.

- [ ] the four images below the main image should be all in one line, each one of them should take 25% of the width.
![image](https://user-images.githubusercontent.com/34653764/92331082-c4137d80-f06b-11ea-87a2-979d6a569920.png)


- [ ] Fix the footer, make the text smaller and have the same color as in the original:

|*Clone*|*Original*|
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/34653764/92331126-31271300-f06c-11ea-85a3-26c710b51820.png) | ![image](https://user-images.githubusercontent.com/34653764/92331120-28364180-f06c-11ea-8832-d398d7a9b372.png) |

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat:

2020-09-06 18:25 UTC, enaburekhan commented
**Code review:**

- Fix footer link color
- Fix input search bar
- They are images and not text 
- The images are well aligned as seen in the read me and attach here
- Fix linter issue
- Fix text alignment inside nav bar

![main-img](https://user-images.githubusercontent.com/51296741/92332532-7bad8d00-f076-11ea-9f1c-53888861185d.png)

2020-09-06 20:10 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] You have a warning in the [HTML Validator](https://validator.w3.org/#validate_by_input), please fix it.

![image](https://user-images.githubusercontent.com/11758151/92333968-7f92dc80-f081-11ea-993c-5a9610ac33f8.png)

- [ ] Elements should be aligned with [float](https://css-tricks.com/all-about-floats/) **and** [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) _or_ [grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/align_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538830/))

- [ ] Your page doesn't seem to be fully aligned together, some sections are wider than the rest, please make them all the same width just like the original page ([link to page](https://web.archive.org/web/20140301004610/http://www.apple.com/))

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-09-06 20:10 UTC, SpaYco commented on index.html
> +        </figure>
- [ ] while these _are_ images, they are also links

- [ ] the text in your demo is different from the page provided 


| Yours | Original |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/11758151/92334169-71de5680-f083-11ea-86e3-bc244fed85e0.png) | ![image](https://user-images.githubusercontent.com/11758151/92334155-56734b80-f083-11ea-8901-0d3de5e226fb.png) |

2020-09-06 20:10 UTC, SpaYco commented on index.html
> +        </div>
- [ ] [Optional] This isn't part of the footer but in the main

2020-09-06 20:10 UTC, Spayco commented on css/style.css
> +}
- [ ] This isn't loading, use `"../images/hero.jpg"` to fix it

2020-09-06 23:40 UTC, enaburekhan commented
**Code review changes effected:**

- Fix html validation warning
- Align images
- Add links to main images
- Fix demo links
- Fix main section layout
- Fix background images to load correctly

2020-09-07 00:18 UTC, Spayco requested changes
# Changes Requested 


Good work! there are two changes you need to do and you're good to go!

## Required Changes ♻️ 

- [ ] sorry I haven't noticed this earlier, but now that the background is fixed, I see that you're not really using it and nothing changes without it, remove the <img> tag that's making the background, and make that CSS property as the background ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/background_image_requirement.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/building-with-backgrounds-and-gradients))  The CSS background should `cover` the whole page irrespective of the screen size. This will be a learning opportunity for the students to use the background size and position properties. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/background_size_requirement.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538830/))

> This is a very important step as this project focuses on building with Backgrounds and Gradients

- [ ] You have files that you're not using anymore, please delete them ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-09-07 09:45 UTC, enaburekhan commented
**Code review changes effected:**

- Fix background image to look the same with the original
![original-apple-image](https://user-images.githubusercontent.com/51296741/92373998-12219300-f0f7-11ea-9d14-8e20f21f4a84.png)

- Remove unused images 

**Attached is the background image and layout from the original page through odin project. This is what we cloned.**

2020-09-07 11:38 UTC, expjazz approved these changes
## Status: Project Approved :clap: 

The page looks great, and I can see that you have implemented all that was previously requested.

You can move on to the next projects :ok: 

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-09-29 09:57 UTC, merged